name: tests_snapshots_create_etalone

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run tests
      env:
          HEADLESS: true  # <-- убираем визуализацию браузера
      run: pytest --browser_name=chrome --force-regen --alluredir=./tests/snapshots/reports tests/snapshots

    # Сохраняем сгенерированные скриншоты как артефакты
    - name: Upload snapshots
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@v4
    with:
      name: reference-snapshots
      path: tests/snapshots/data/
      retention-days: 7

    # Коммитим новые или обновлённые скриншоты в репозиторий
    - name: Commit snapshots
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "lexun2@yandex.ru"
        git add tests/snapshots/data/*
        git diff --staged --quiet || git commit -m "Update reference snapshots [ci skip]"
        git push
      continue-on-error: true